### ISSUE TITLE
"Frameworks/IOKit" is missing

### ISSUE THREAD

**Issue by aleclarson** [w0lfschild/macOS_headers#1]
https://developer.apple.com/documentation/iokit

**Comment by aleclarson** [comment]
"PrivateFrameworks/DisplayServices" is also missing

**Comment by w0lfschild** [comment]
Hmm. I'll look into that, this repository is just updated by a script automatically so I haven't looked at it in quite a while.

**Comment by w0lfschild** [comment]
Just did an overhaul of the scripts. Should fix the missing frameworks as well as actually dump protected apps and swift binaries.

Hopefully this is more complete but I wouldn't be surprised if there are still missing frameworks.
