### ISSUE TITLE
Consider adding /System/Applications to dumped locations

### ISSUE THREAD

**Issue by LeoNatan** [w0lfschild/macOS_headers#2]
Hello,

System apps now sit under /System/Applications, rather than /Applications

https://github.com/w0lfschild/macOS_headers/blob/1233f821ced3ea6b419790e173512ea495ba19b8/tools/header_dump.sh#L122

**Comment by w0lfschild** [comment]
Done.

Next time there's an update that path will be included.

**Comment by LeoNatan** [comment]
Great, thanks!

**Comment by LeoNatan** [comment]
Haha, but /Applications/Utilities is now really /System/Applications/Utilities
That one should be added also.

**Comment by w0lfschild** [comment]
I've added that as well, thanks for pointing that out.
